/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Stuff;

import Connection_to_Database.DB_Manager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException;

/**
 *
 * @author Admin
 */
public class Course_Add_Remove extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Course_Add_Remove() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_Info = new javax.swing.JLabel();
        Student_ID = new javax.swing.JLabel();
        First_Name = new javax.swing.JLabel();
        Last_Name = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone_num = new javax.swing.JTextField();
        telephone_num = new javax.swing.JLabel();
        stud_id = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        f_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Add_Info1 = new javax.swing.JLabel();
        Student_ID1 = new javax.swing.JLabel();
        First_Name1 = new javax.swing.JLabel();
        Last_Name1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();
        telephone_num1 = new javax.swing.JLabel();
        Course_Code = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        Course_Name = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Main_Menu = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Year = new javax.swing.JComboBox<>();
        Sem = new javax.swing.JComboBox<>();
        Combo = new javax.swing.JComboBox<>();

        Add_Info.setText("                     Add Information Here");

        Student_ID.setText("StudentID");

        First_Name.setText("First Name");

        Last_Name.setText("Last Name");

        Address.setText("Address");

        telephone_num.setText("Phone Number");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Code", "Course Name", "Price", "Year", "Semester"
            }
        ));
        jScrollPane1.setViewportView(Table);

        Add_Info1.setText("                     Add Information Here");

        Student_ID1.setText("Course Code");

        First_Name1.setText("Course Name");

        Last_Name1.setText("Price");

        Address1.setText("Year");

        telephone_num1.setText("Semester");

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Main_Menu.setText("Main Menu");
        Main_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenuActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        jLabel1.setText("First Select Row from JTable then press Remove Button");

        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4", "Any" }));
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });

        Sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem 1", "Sem 2", "Any" }));

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENME", "ENEL", "ENGE", "ENSE", "COMP" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Sem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Address1)
                                .addGap(23, 23, 23))
                            .addComponent(telephone_num1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Year, javax.swing.GroupLayout.Alignment.LEADING, 0, 66, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Course_Name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Last_Name1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(First_Name1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Add_Info1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Add, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Student_ID1)
                                        .addComponent(Course_Code, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Main_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Add_Info1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(Student_ID1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Course_Code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(First_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Course_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Last_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(telephone_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1387, 647));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      
    }//GEN-LAST:event_addActionPerformed
  //Ignore white space method which allows a string which contains spaces to be squished together
    public static String ignoreWhiteSpace(String s){
        String ignored = "";
        //for loop that iterates throught the length of the string searching for whitespace.
        for(int i = 0; i<s.length(); i++){
            if(!Character.isWhitespace(s.charAt(i))){
                ignored+=s.charAt(i);
            }
        }
        return ignored;
    }
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        //setting price to 0
        float price = 0;
        // declaring below variables
        String crse_id = Course_Code.getText().trim();
        String crse_name = ignoreWhiteSpace(Course_Name.getText().trim());
        String courses = (String) Combo.getSelectedItem();
        String year = (String) Year.getSelectedItem();
        String semester = (String) Sem.getSelectedItem();
        //String builder so that I can put the concatenated string into the sql statement. 
        String building = new StringBuilder().append(courses).append(crse_id).toString();
        
        try{
            // parsing price so that it can be used in the sql statement
            price = Float.parseFloat(Price.getText().trim());
        }
        // catch method that is meant to catch Strings in integer text fields.
        catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null, "Please enter an integer");
              //refreshes page
              this.setVisible(false);
              new Course_Add_Remove().setVisible(true);
        }
        try {
            //initialising connection
            Connection conn = DriverManager.getConnection("jdbc:derby:CourseDB_Ebd ;create=true", "pdc", "pdc");
            Statement st = conn.createStatement();
            // if statement to check if the declared variables are empty if so run error message not all fields have been submitted 
            if(crse_id.isEmpty() || crse_name.isEmpty() || Price.getText().equals(" ") || year.isEmpty() || semester.isEmpty())
            {
                JOptionPane.showMessageDialog(null,"Not all fields have been submitted");
            }
            // If course_code does not equal 3, User is let known that he/she has to reinput the value
            else if(Course_Code.getText().length() > 3 || Course_Code.getText().length() < 3) {
            JOptionPane.showMessageDialog(null, "Please enter a 3 number digit");
            }
            //else if statement made for course names as it should not accept any numbers.
            else if(!crse_name.matches("[a-zA-z]+")){
            JOptionPane.showMessageDialog(null, "Please enter a String");
            }
            else{
                // exectuting statement
               st.execute("INSERT INTO COURSES VALUES ('"+building+"','"+crse_name+"',"+price+",'"+year+"','"+semester+"')");
               //Option Pane that displays that the Course has been registered 
               JOptionPane.showMessageDialog(null, "Course Registered.");
                setVisible(false);
                new Course_Add_Remove().setVisible(true);  
            }
            }
        //Handling SQL Exception
         catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       
        /*
        SAME EXACT CONCEPT AS PREVIOUS CLASS
        */
        Connection conn = null;   
         ResultSet rs = null;
        try {
            DB_Manager manage = new DB_Manager();
            String logging = "SELECT *FROM COURSES"; 
            conn = manage.getConnection(); 
                 System.out.println("jdbc:derby:CourseDB_Ebd; create=true" + " Connection Established");
              PreparedStatement st = conn.prepareStatement(logging);
              rs = st.executeQuery();
             
            DefaultTableModel model = (DefaultTableModel) Table.getModel();

       
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getFloat(3), rs.getString(4), rs.getString(5)});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void Main_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenuActionPerformed
       // Going to Admin menu.
        setVisible(false);
       new Admin().setVisible(true);
    }//GEN-LAST:event_Main_MenuActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
     
     //Delete method that deletes from COURSES
      try{
          int row = Table.getSelectedRow();
          String cell = Table.getModel().getValueAt(row, 2).toString();
          String delete = "DELETE FROM COURSES WHERE PRICE= " + cell;
         // Establishing Connection
          Connection conn = DriverManager.getConnection("jdbc:derby:CourseDB_Ebd ;create=true", "pdc", "pdc");
          //Prepare Statement
          PreparedStatement prepared = conn.prepareStatement(delete);
          // Execute Statement
          prepared.execute();
          setVisible(false);
          new Course_Add_Remove().setVisible(true);
      }
       catch(DerbySQLIntegrityConstraintViolationException ex){
         JOptionPane.showMessageDialog(null,"You have inserted a duplicate please enter another value");
     }
      catch(ArrayIndexOutOfBoundsException ex){
          JOptionPane.showMessageDialog(null, "Please select a row before you delete");
      } catch (SQLException ex) {
            Logger.getLogger(Course_Add_Remove.class.getName()).log(Level.SEVERE, null, ex);
        }
      
             
    }//GEN-LAST:event_RemoveActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Course_Add_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Course_Add_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Course_Add_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Course_Add_Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Course_Add_Remove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Add_Info;
    private javax.swing.JLabel Add_Info1;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JTextField Course_Code;
    private javax.swing.JTextField Course_Name;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel First_Name;
    private javax.swing.JLabel First_Name1;
    private javax.swing.JLabel Last_Name;
    private javax.swing.JLabel Last_Name1;
    private javax.swing.JButton Main_Menu;
    private javax.swing.JTextField Price;
    private javax.swing.JButton Remove;
    private javax.swing.JComboBox<String> Sem;
    private javax.swing.JLabel Student_ID;
    private javax.swing.JLabel Student_ID1;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JTextField f_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField phone_num;
    private javax.swing.JTextField stud_id;
    private javax.swing.JLabel telephone_num;
    private javax.swing.JLabel telephone_num1;
    // End of variables declaration//GEN-END:variables
}
